### ISSUE TITLE
ReduxSimple v3

### ISSUE THREAD

**Issue by Odonno** [Feroks/Blazor-Reactive-Omdb#1]
Hi @Feroks 

I saw you used ReduxSimple on this repository. I opened this issue to let you know that ReduxSimple is now in v3 with a ton of new features added:

* Simplified constructor (with time travel as an option)
* Enhanced reducers (following the `On` pattern inspired by @ngrx, nested/sub reducers)
* A powerful feature: selectors (memoized selectors, memoized selectors with props, combined selectors)
* Effects (asynchronous actions)
* Entity management in the state (currently in preview)
* Router Store (currently in preview, for UWP)
* DevTools (currently in preview, for UWP)

There is also some small breaking changes, like `ObserveState` method is now renamed as `Select`.

If I am not wrong, I can see you use Blazor on this project. If you are open to discussion, I would like to know how you ReduxSimple with Blazor and if there is anything I can do to improve your experience of ReduxSimple in Blazor.

Thank you.

**Comment by Feroks** [comment]
Hey @Odonno 

Thank you for the message! This project is just a simple playground for Blazor, but I have other apps that use your library and I will definitely use those new features.

Nonetheless, I have updated the code in this repository. Few things I have noticed:

- In order to use `On<>`, `CreateEffect<>` you need to have `using static ReduxSimple.Effects;`. Until you specify it explicitly, intelllisene gives you wrong method. Took me a while to figure it out :)

- It is not possible to inherit `ReduxStore`. It is not a big deal, but it makes it impossible to inject 'named' store, need to write `ReduxStore<MyState>` in constructor.

- I had an issue with Reactive package, because i am using 4.2.0 and you have 3.1.1. In order to make it work i needed to install `System.Reactive.Compatibility`, just FYI.

**Comment by Odonno** [comment]
1. In order to use `On<>`, `CreateEffect<>` you need to have `using static ReduxSimple.Effects;`. Until you specify it explicitly, intelllisene gives you wrong method. Took me a while to figure it out :)

Indeed, there is quite some static functions in the library and you have to add `using static` yourself. There are some of them you need to know:

```
using static ReduxSimple.Effects;
using static ReduxSimple.Reducers;
using static ReduxSimple.Selectors;
```

I hope that Visual Studio can auto-detect these in the future like they do with classes/interfaces/etc..
Otherwise, I can try to write a tutorial with step-by-step code to write a ReduxSimple app with every features inside the library: state, reducers, selectors, effects, etc..

2. It is not possible to inherit `ReduxStore`. It is not a big deal, but it makes it impossible to inject 'named' store, need to write `ReduxStore<MyState>` in constructor.

Well, it is by design. Redux pattern is based on a single source of truth, so a single instance at a time. What you can do is to call your store in the `Using` list:

```
using TodoStore = ReduxStore<TodoState>;
```

3. I had an issue with Reactive package, because i am using 4.2.0 and you have 3.1.1. In order to make it work i needed to install `System.Reactive.Compatibility`, just FYI.

Good to know. I don't see the differences between the two versions. I'll try to update to v4 of `System.Reactive` when the time comes.

**Comment by Odonno** [comment]
Just to let you know `ReduxSimple` is upgraded to v3.3. Nothing fancy, I updated the dependencies like `System.Reactive` to the latest version.
